# Generated by Django 4.1.8 on 2023-05-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_followuser"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="followuser",
            constraint=models.UniqueConstraint(fields=("follower", "following"), name="unique_FollowUser"),
        ),
    ]
