# Generated by Django 4.2 on 2023-04-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tweets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="title",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
